#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StudentManagement")]
	public partial class dbStudentManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDiem(Diem instance);
    partial void UpdateDiem(Diem instance);
    partial void DeleteDiem(Diem instance);
    partial void InsertDiemDanh(DiemDanh instance);
    partial void UpdateDiemDanh(DiemDanh instance);
    partial void DeleteDiemDanh(DiemDanh instance);
    partial void InsertGiaoVien(GiaoVien instance);
    partial void UpdateGiaoVien(GiaoVien instance);
    partial void DeleteGiaoVien(GiaoVien instance);
    partial void InsertGV_Mon(GV_Mon instance);
    partial void UpdateGV_Mon(GV_Mon instance);
    partial void DeleteGV_Mon(GV_Mon instance);
    partial void InsertGV_Mon_Lop(GV_Mon_Lop instance);
    partial void UpdateGV_Mon_Lop(GV_Mon_Lop instance);
    partial void DeleteGV_Mon_Lop(GV_Mon_Lop instance);
    partial void InsertHeDaoTao(HeDaoTao instance);
    partial void UpdateHeDaoTao(HeDaoTao instance);
    partial void DeleteHeDaoTao(HeDaoTao instance);
    partial void InsertKhoa(Khoa instance);
    partial void UpdateKhoa(Khoa instance);
    partial void DeleteKhoa(Khoa instance);
    partial void InsertLopHoc(LopHoc instance);
    partial void UpdateLopHoc(LopHoc instance);
    partial void DeleteLopHoc(LopHoc instance);
    partial void InsertMonHoc(MonHoc instance);
    partial void UpdateMonHoc(MonHoc instance);
    partial void DeleteMonHoc(MonHoc instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public dbStudentManagementDataContext() : 
				base(global::StudentManagement.Properties.Settings.Default.StudentManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbStudentManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbStudentManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbStudentManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbStudentManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Diem> Diems
		{
			get
			{
				return this.GetTable<Diem>();
			}
		}
		
		public System.Data.Linq.Table<DiemDanh> DiemDanhs
		{
			get
			{
				return this.GetTable<DiemDanh>();
			}
		}
		
		public System.Data.Linq.Table<GiaoVien> GiaoViens
		{
			get
			{
				return this.GetTable<GiaoVien>();
			}
		}
		
		public System.Data.Linq.Table<GV_Mon> GV_Mons
		{
			get
			{
				return this.GetTable<GV_Mon>();
			}
		}
		
		public System.Data.Linq.Table<GV_Mon_Lop> GV_Mon_Lops
		{
			get
			{
				return this.GetTable<GV_Mon_Lop>();
			}
		}
		
		public System.Data.Linq.Table<HeDaoTao> HeDaoTaos
		{
			get
			{
				return this.GetTable<HeDaoTao>();
			}
		}
		
		public System.Data.Linq.Table<Khoa> Khoas
		{
			get
			{
				return this.GetTable<Khoa>();
			}
		}
		
		public System.Data.Linq.Table<LopHoc> LopHocs
		{
			get
			{
				return this.GetTable<LopHoc>();
			}
		}
		
		public System.Data.Linq.Table<MonHoc> MonHocs
		{
			get
			{
				return this.GetTable<MonHoc>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Diem")]
	public partial class Diem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maDiem;
		
		private System.Nullable<int> _loaiDiem;
		
		private System.Nullable<int> _diemSo;
		
		private System.Nullable<int> _soLanThi;
		
		private System.Nullable<int> _maSV;
		
		private System.Nullable<int> _maMonHoc;
		
		private EntityRef<MonHoc> _MonHoc;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDiemChanging(int value);
    partial void OnmaDiemChanged();
    partial void OnloaiDiemChanging(System.Nullable<int> value);
    partial void OnloaiDiemChanged();
    partial void OndiemSoChanging(System.Nullable<int> value);
    partial void OndiemSoChanged();
    partial void OnsoLanThiChanging(System.Nullable<int> value);
    partial void OnsoLanThiChanged();
    partial void OnmaSVChanging(System.Nullable<int> value);
    partial void OnmaSVChanged();
    partial void OnmaMonHocChanging(System.Nullable<int> value);
    partial void OnmaMonHocChanged();
    #endregion
		
		public Diem()
		{
			this._MonHoc = default(EntityRef<MonHoc>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDiem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maDiem
		{
			get
			{
				return this._maDiem;
			}
			set
			{
				if ((this._maDiem != value))
				{
					this.OnmaDiemChanging(value);
					this.SendPropertyChanging();
					this._maDiem = value;
					this.SendPropertyChanged("maDiem");
					this.OnmaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiDiem", DbType="Int")]
		public System.Nullable<int> loaiDiem
		{
			get
			{
				return this._loaiDiem;
			}
			set
			{
				if ((this._loaiDiem != value))
				{
					this.OnloaiDiemChanging(value);
					this.SendPropertyChanging();
					this._loaiDiem = value;
					this.SendPropertyChanged("loaiDiem");
					this.OnloaiDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemSo", DbType="Int")]
		public System.Nullable<int> diemSo
		{
			get
			{
				return this._diemSo;
			}
			set
			{
				if ((this._diemSo != value))
				{
					this.OndiemSoChanging(value);
					this.SendPropertyChanging();
					this._diemSo = value;
					this.SendPropertyChanged("diemSo");
					this.OndiemSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLanThi", DbType="Int")]
		public System.Nullable<int> soLanThi
		{
			get
			{
				return this._soLanThi;
			}
			set
			{
				if ((this._soLanThi != value))
				{
					this.OnsoLanThiChanging(value);
					this.SendPropertyChanging();
					this._soLanThi = value;
					this.SendPropertyChanged("soLanThi");
					this.OnsoLanThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="Int")]
		public System.Nullable<int> maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonHoc", DbType="Int")]
		public System.Nullable<int> maMonHoc
		{
			get
			{
				return this._maMonHoc;
			}
			set
			{
				if ((this._maMonHoc != value))
				{
					if (this._MonHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaMonHocChanging(value);
					this.SendPropertyChanging();
					this._maMonHoc = value;
					this.SendPropertyChanged("maMonHoc");
					this.OnmaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_Diem", Storage="_MonHoc", ThisKey="maMonHoc", OtherKey="maMonHoc", IsForeignKey=true)]
		public MonHoc MonHoc
		{
			get
			{
				return this._MonHoc.Entity;
			}
			set
			{
				MonHoc previousValue = this._MonHoc.Entity;
				if (((previousValue != value) 
							|| (this._MonHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonHoc.Entity = null;
						previousValue.Diems.Remove(this);
					}
					this._MonHoc.Entity = value;
					if ((value != null))
					{
						value.Diems.Add(this);
						this._maMonHoc = value.maMonHoc;
					}
					else
					{
						this._maMonHoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("MonHoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_Diem", Storage="_SinhVien", ThisKey="maSV", OtherKey="maSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.Diems.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.Diems.Add(this);
						this._maSV = value.maSV;
					}
					else
					{
						this._maSV = default(Nullable<int>);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiemDanh")]
	public partial class DiemDanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maDD;
		
		private System.Nullable<System.DateTime> _ngayDD;
		
		private System.Nullable<int> _soBuoi;
		
		private string _ghiDiemDanh;
		
		private string _ghiChu;
		
		private System.Nullable<int> _maSV;
		
		private System.Nullable<int> _maMonHoc;
		
		private EntityRef<MonHoc> _MonHoc;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDDChanging(int value);
    partial void OnmaDDChanged();
    partial void OnngayDDChanging(System.Nullable<System.DateTime> value);
    partial void OnngayDDChanged();
    partial void OnsoBuoiChanging(System.Nullable<int> value);
    partial void OnsoBuoiChanged();
    partial void OnghiDiemDanhChanging(string value);
    partial void OnghiDiemDanhChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OnmaSVChanging(System.Nullable<int> value);
    partial void OnmaSVChanged();
    partial void OnmaMonHocChanging(System.Nullable<int> value);
    partial void OnmaMonHocChanged();
    #endregion
		
		public DiemDanh()
		{
			this._MonHoc = default(EntityRef<MonHoc>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maDD
		{
			get
			{
				return this._maDD;
			}
			set
			{
				if ((this._maDD != value))
				{
					this.OnmaDDChanging(value);
					this.SendPropertyChanging();
					this._maDD = value;
					this.SendPropertyChanged("maDD");
					this.OnmaDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDD", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayDD
		{
			get
			{
				return this._ngayDD;
			}
			set
			{
				if ((this._ngayDD != value))
				{
					this.OnngayDDChanging(value);
					this.SendPropertyChanging();
					this._ngayDD = value;
					this.SendPropertyChanged("ngayDD");
					this.OnngayDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soBuoi", DbType="Int")]
		public System.Nullable<int> soBuoi
		{
			get
			{
				return this._soBuoi;
			}
			set
			{
				if ((this._soBuoi != value))
				{
					this.OnsoBuoiChanging(value);
					this.SendPropertyChanging();
					this._soBuoi = value;
					this.SendPropertyChanged("soBuoi");
					this.OnsoBuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiDiemDanh", DbType="VarChar(2)")]
		public string ghiDiemDanh
		{
			get
			{
				return this._ghiDiemDanh;
			}
			set
			{
				if ((this._ghiDiemDanh != value))
				{
					this.OnghiDiemDanhChanging(value);
					this.SendPropertyChanging();
					this._ghiDiemDanh = value;
					this.SendPropertyChanged("ghiDiemDanh");
					this.OnghiDiemDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(1)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="Int")]
		public System.Nullable<int> maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonHoc", DbType="Int")]
		public System.Nullable<int> maMonHoc
		{
			get
			{
				return this._maMonHoc;
			}
			set
			{
				if ((this._maMonHoc != value))
				{
					if (this._MonHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaMonHocChanging(value);
					this.SendPropertyChanging();
					this._maMonHoc = value;
					this.SendPropertyChanged("maMonHoc");
					this.OnmaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_DiemDanh", Storage="_MonHoc", ThisKey="maMonHoc", OtherKey="maMonHoc", IsForeignKey=true)]
		public MonHoc MonHoc
		{
			get
			{
				return this._MonHoc.Entity;
			}
			set
			{
				MonHoc previousValue = this._MonHoc.Entity;
				if (((previousValue != value) 
							|| (this._MonHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonHoc.Entity = null;
						previousValue.DiemDanhs.Remove(this);
					}
					this._MonHoc.Entity = value;
					if ((value != null))
					{
						value.DiemDanhs.Add(this);
						this._maMonHoc = value.maMonHoc;
					}
					else
					{
						this._maMonHoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("MonHoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DiemDanh", Storage="_SinhVien", ThisKey="maSV", OtherKey="maSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.DiemDanhs.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.DiemDanhs.Add(this);
						this._maSV = value.maSV;
					}
					else
					{
						this._maSV = default(Nullable<int>);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaoVien")]
	public partial class GiaoVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maGV;
		
		private string _tenGV;
		
		private System.Nullable<bool> _gioiTinh;
		
		private System.Nullable<System.DateTime> _sinhNhat;
		
		private string _diaChi;
		
		private System.Nullable<int> _soCMT;
		
		private System.Nullable<int> _dienThoai;
		
		private string _email;
		
		private string _password;
		
		private System.Nullable<int> _trangThai;
		
		private EntitySet<GV_Mon> _GV_Mons;
		
		private EntitySet<GV_Mon_Lop> _GV_Mon_Lops;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaGVChanging(int value);
    partial void OnmaGVChanged();
    partial void OntenGVChanging(string value);
    partial void OntenGVChanged();
    partial void OngioiTinhChanging(System.Nullable<bool> value);
    partial void OngioiTinhChanged();
    partial void OnsinhNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnsinhNhatChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsoCMTChanging(System.Nullable<int> value);
    partial void OnsoCMTChanged();
    partial void OndienThoaiChanging(System.Nullable<int> value);
    partial void OndienThoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public GiaoVien()
		{
			this._GV_Mons = new EntitySet<GV_Mon>(new Action<GV_Mon>(this.attach_GV_Mons), new Action<GV_Mon>(this.detach_GV_Mons));
			this._GV_Mon_Lops = new EntitySet<GV_Mon_Lop>(new Action<GV_Mon_Lop>(this.attach_GV_Mon_Lops), new Action<GV_Mon_Lop>(this.detach_GV_Mon_Lops));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maGV
		{
			get
			{
				return this._maGV;
			}
			set
			{
				if ((this._maGV != value))
				{
					this.OnmaGVChanging(value);
					this.SendPropertyChanging();
					this._maGV = value;
					this.SendPropertyChanged("maGV");
					this.OnmaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenGV", DbType="NVarChar(100)")]
		public string tenGV
		{
			get
			{
				return this._tenGV;
			}
			set
			{
				if ((this._tenGV != value))
				{
					this.OntenGVChanging(value);
					this.SendPropertyChanging();
					this._tenGV = value;
					this.SendPropertyChanged("tenGV");
					this.OntenGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="Bit")]
		public System.Nullable<bool> gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinhNhat", DbType="Date")]
		public System.Nullable<System.DateTime> sinhNhat
		{
			get
			{
				return this._sinhNhat;
			}
			set
			{
				if ((this._sinhNhat != value))
				{
					this.OnsinhNhatChanging(value);
					this.SendPropertyChanging();
					this._sinhNhat = value;
					this.SendPropertyChanged("sinhNhat");
					this.OnsinhNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(300)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCMT", DbType="Int")]
		public System.Nullable<int> soCMT
		{
			get
			{
				return this._soCMT;
			}
			set
			{
				if ((this._soCMT != value))
				{
					this.OnsoCMTChanging(value);
					this.SendPropertyChanging();
					this._soCMT = value;
					this.SendPropertyChanged("soCMT");
					this.OnsoCMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienThoai", DbType="Int")]
		public System.Nullable<int> dienThoai
		{
			get
			{
				return this._dienThoai;
			}
			set
			{
				if ((this._dienThoai != value))
				{
					this.OndienThoaiChanging(value);
					this.SendPropertyChanging();
					this._dienThoai = value;
					this.SendPropertyChanged("dienThoai");
					this.OndienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(200)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(200)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_GV_Mon", Storage="_GV_Mons", ThisKey="maGV", OtherKey="maGV")]
		public EntitySet<GV_Mon> GV_Mons
		{
			get
			{
				return this._GV_Mons;
			}
			set
			{
				this._GV_Mons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_GV_Mon_Lop", Storage="_GV_Mon_Lops", ThisKey="maGV", OtherKey="maGV")]
		public EntitySet<GV_Mon_Lop> GV_Mon_Lops
		{
			get
			{
				return this._GV_Mon_Lops;
			}
			set
			{
				this._GV_Mon_Lops.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GV_Mons(GV_Mon entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = this;
		}
		
		private void detach_GV_Mons(GV_Mon entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = null;
		}
		
		private void attach_GV_Mon_Lops(GV_Mon_Lop entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = this;
		}
		
		private void detach_GV_Mon_Lops(GV_Mon_Lop entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GV_Mon")]
	public partial class GV_Mon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maGV_M;
		
		private System.Nullable<int> _maGV;
		
		private System.Nullable<int> _maMonHoc;
		
		private EntityRef<GiaoVien> _GiaoVien;
		
		private EntityRef<MonHoc> _MonHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaGV_MChanging(int value);
    partial void OnmaGV_MChanged();
    partial void OnmaGVChanging(System.Nullable<int> value);
    partial void OnmaGVChanged();
    partial void OnmaMonHocChanging(System.Nullable<int> value);
    partial void OnmaMonHocChanged();
    #endregion
		
		public GV_Mon()
		{
			this._GiaoVien = default(EntityRef<GiaoVien>);
			this._MonHoc = default(EntityRef<MonHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGV_M", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maGV_M
		{
			get
			{
				return this._maGV_M;
			}
			set
			{
				if ((this._maGV_M != value))
				{
					this.OnmaGV_MChanging(value);
					this.SendPropertyChanging();
					this._maGV_M = value;
					this.SendPropertyChanged("maGV_M");
					this.OnmaGV_MChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGV", DbType="Int")]
		public System.Nullable<int> maGV
		{
			get
			{
				return this._maGV;
			}
			set
			{
				if ((this._maGV != value))
				{
					if (this._GiaoVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaGVChanging(value);
					this.SendPropertyChanging();
					this._maGV = value;
					this.SendPropertyChanged("maGV");
					this.OnmaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonHoc", DbType="Int")]
		public System.Nullable<int> maMonHoc
		{
			get
			{
				return this._maMonHoc;
			}
			set
			{
				if ((this._maMonHoc != value))
				{
					if (this._MonHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaMonHocChanging(value);
					this.SendPropertyChanging();
					this._maMonHoc = value;
					this.SendPropertyChanged("maMonHoc");
					this.OnmaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_GV_Mon", Storage="_GiaoVien", ThisKey="maGV", OtherKey="maGV", IsForeignKey=true)]
		public GiaoVien GiaoVien
		{
			get
			{
				return this._GiaoVien.Entity;
			}
			set
			{
				GiaoVien previousValue = this._GiaoVien.Entity;
				if (((previousValue != value) 
							|| (this._GiaoVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiaoVien.Entity = null;
						previousValue.GV_Mons.Remove(this);
					}
					this._GiaoVien.Entity = value;
					if ((value != null))
					{
						value.GV_Mons.Add(this);
						this._maGV = value.maGV;
					}
					else
					{
						this._maGV = default(Nullable<int>);
					}
					this.SendPropertyChanged("GiaoVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_GV_Mon", Storage="_MonHoc", ThisKey="maMonHoc", OtherKey="maMonHoc", IsForeignKey=true)]
		public MonHoc MonHoc
		{
			get
			{
				return this._MonHoc.Entity;
			}
			set
			{
				MonHoc previousValue = this._MonHoc.Entity;
				if (((previousValue != value) 
							|| (this._MonHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonHoc.Entity = null;
						previousValue.GV_Mons.Remove(this);
					}
					this._MonHoc.Entity = value;
					if ((value != null))
					{
						value.GV_Mons.Add(this);
						this._maMonHoc = value.maMonHoc;
					}
					else
					{
						this._maMonHoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("MonHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GV_Mon_Lop")]
	public partial class GV_Mon_Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maGV_M_L;
		
		private System.Nullable<int> _maGV;
		
		private System.Nullable<int> _maMonHoc;
		
		private System.Nullable<int> _maLopHoc;
		
		private EntityRef<GiaoVien> _GiaoVien;
		
		private EntityRef<LopHoc> _LopHoc;
		
		private EntityRef<MonHoc> _MonHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaGV_M_LChanging(int value);
    partial void OnmaGV_M_LChanged();
    partial void OnmaGVChanging(System.Nullable<int> value);
    partial void OnmaGVChanged();
    partial void OnmaMonHocChanging(System.Nullable<int> value);
    partial void OnmaMonHocChanged();
    partial void OnmaLopHocChanging(System.Nullable<int> value);
    partial void OnmaLopHocChanged();
    #endregion
		
		public GV_Mon_Lop()
		{
			this._GiaoVien = default(EntityRef<GiaoVien>);
			this._LopHoc = default(EntityRef<LopHoc>);
			this._MonHoc = default(EntityRef<MonHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGV_M_L", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maGV_M_L
		{
			get
			{
				return this._maGV_M_L;
			}
			set
			{
				if ((this._maGV_M_L != value))
				{
					this.OnmaGV_M_LChanging(value);
					this.SendPropertyChanging();
					this._maGV_M_L = value;
					this.SendPropertyChanged("maGV_M_L");
					this.OnmaGV_M_LChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGV", DbType="Int")]
		public System.Nullable<int> maGV
		{
			get
			{
				return this._maGV;
			}
			set
			{
				if ((this._maGV != value))
				{
					if (this._GiaoVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaGVChanging(value);
					this.SendPropertyChanging();
					this._maGV = value;
					this.SendPropertyChanged("maGV");
					this.OnmaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonHoc", DbType="Int")]
		public System.Nullable<int> maMonHoc
		{
			get
			{
				return this._maMonHoc;
			}
			set
			{
				if ((this._maMonHoc != value))
				{
					if (this._MonHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaMonHocChanging(value);
					this.SendPropertyChanging();
					this._maMonHoc = value;
					this.SendPropertyChanged("maMonHoc");
					this.OnmaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLopHoc", DbType="Int")]
		public System.Nullable<int> maLopHoc
		{
			get
			{
				return this._maLopHoc;
			}
			set
			{
				if ((this._maLopHoc != value))
				{
					if (this._LopHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLopHocChanging(value);
					this.SendPropertyChanging();
					this._maLopHoc = value;
					this.SendPropertyChanged("maLopHoc");
					this.OnmaLopHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_GV_Mon_Lop", Storage="_GiaoVien", ThisKey="maGV", OtherKey="maGV", IsForeignKey=true)]
		public GiaoVien GiaoVien
		{
			get
			{
				return this._GiaoVien.Entity;
			}
			set
			{
				GiaoVien previousValue = this._GiaoVien.Entity;
				if (((previousValue != value) 
							|| (this._GiaoVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiaoVien.Entity = null;
						previousValue.GV_Mon_Lops.Remove(this);
					}
					this._GiaoVien.Entity = value;
					if ((value != null))
					{
						value.GV_Mon_Lops.Add(this);
						this._maGV = value.maGV;
					}
					else
					{
						this._maGV = default(Nullable<int>);
					}
					this.SendPropertyChanged("GiaoVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_GV_Mon_Lop", Storage="_LopHoc", ThisKey="maLopHoc", OtherKey="maLopHoc", IsForeignKey=true)]
		public LopHoc LopHoc
		{
			get
			{
				return this._LopHoc.Entity;
			}
			set
			{
				LopHoc previousValue = this._LopHoc.Entity;
				if (((previousValue != value) 
							|| (this._LopHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LopHoc.Entity = null;
						previousValue.GV_Mon_Lops.Remove(this);
					}
					this._LopHoc.Entity = value;
					if ((value != null))
					{
						value.GV_Mon_Lops.Add(this);
						this._maLopHoc = value.maLopHoc;
					}
					else
					{
						this._maLopHoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("LopHoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_GV_Mon_Lop", Storage="_MonHoc", ThisKey="maMonHoc", OtherKey="maMonHoc", IsForeignKey=true)]
		public MonHoc MonHoc
		{
			get
			{
				return this._MonHoc.Entity;
			}
			set
			{
				MonHoc previousValue = this._MonHoc.Entity;
				if (((previousValue != value) 
							|| (this._MonHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonHoc.Entity = null;
						previousValue.GV_Mon_Lops.Remove(this);
					}
					this._MonHoc.Entity = value;
					if ((value != null))
					{
						value.GV_Mon_Lops.Add(this);
						this._maMonHoc = value.maMonHoc;
					}
					else
					{
						this._maMonHoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("MonHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HeDaoTao")]
	public partial class HeDaoTao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHe;
		
		private string _tenHeDaoTao;
		
		private System.Nullable<int> _soHocKy;
		
		private System.Nullable<int> _trangThai;
		
		private EntitySet<LopHoc> _LopHocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHeChanging(int value);
    partial void OnmaHeChanged();
    partial void OntenHeDaoTaoChanging(string value);
    partial void OntenHeDaoTaoChanged();
    partial void OnsoHocKyChanging(System.Nullable<int> value);
    partial void OnsoHocKyChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public HeDaoTao()
		{
			this._LopHocs = new EntitySet<LopHoc>(new Action<LopHoc>(this.attach_LopHocs), new Action<LopHoc>(this.detach_LopHocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maHe
		{
			get
			{
				return this._maHe;
			}
			set
			{
				if ((this._maHe != value))
				{
					this.OnmaHeChanging(value);
					this.SendPropertyChanging();
					this._maHe = value;
					this.SendPropertyChanged("maHe");
					this.OnmaHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHeDaoTao", DbType="NVarChar(100)")]
		public string tenHeDaoTao
		{
			get
			{
				return this._tenHeDaoTao;
			}
			set
			{
				if ((this._tenHeDaoTao != value))
				{
					this.OntenHeDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._tenHeDaoTao = value;
					this.SendPropertyChanged("tenHeDaoTao");
					this.OntenHeDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soHocKy", DbType="Int")]
		public System.Nullable<int> soHocKy
		{
			get
			{
				return this._soHocKy;
			}
			set
			{
				if ((this._soHocKy != value))
				{
					this.OnsoHocKyChanging(value);
					this.SendPropertyChanging();
					this._soHocKy = value;
					this.SendPropertyChanged("soHocKy");
					this.OnsoHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HeDaoTao_LopHoc", Storage="_LopHocs", ThisKey="maHe", OtherKey="maHe")]
		public EntitySet<LopHoc> LopHocs
		{
			get
			{
				return this._LopHocs;
			}
			set
			{
				this._LopHocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LopHocs(LopHoc entity)
		{
			this.SendPropertyChanging();
			entity.HeDaoTao = this;
		}
		
		private void detach_LopHocs(LopHoc entity)
		{
			this.SendPropertyChanging();
			entity.HeDaoTao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoa")]
	public partial class Khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maKhoa;
		
		private string _tenKhoa;
		
		private System.Nullable<int> _trangThai;
		
		private EntitySet<LopHoc> _LopHocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhoaChanging(int value);
    partial void OnmaKhoaChanged();
    partial void OntenKhoaChanging(string value);
    partial void OntenKhoaChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public Khoa()
		{
			this._LopHocs = new EntitySet<LopHoc>(new Action<LopHoc>(this.attach_LopHocs), new Action<LopHoc>(this.detach_LopHocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhoa", DbType="NVarChar(200)")]
		public string tenKhoa
		{
			get
			{
				return this._tenKhoa;
			}
			set
			{
				if ((this._tenKhoa != value))
				{
					this.OntenKhoaChanging(value);
					this.SendPropertyChanging();
					this._tenKhoa = value;
					this.SendPropertyChanged("tenKhoa");
					this.OntenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_LopHoc", Storage="_LopHocs", ThisKey="maKhoa", OtherKey="maKhoa")]
		public EntitySet<LopHoc> LopHocs
		{
			get
			{
				return this._LopHocs;
			}
			set
			{
				this._LopHocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LopHocs(LopHoc entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_LopHocs(LopHoc entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LopHoc")]
	public partial class LopHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maLopHoc;
		
		private string _tenLop;
		
		private System.Nullable<System.DateTime> _khaiGiang;
		
		private System.Nullable<System.DateTime> _totNghiep;
		
		private System.Nullable<int> _trangThai;
		
		private System.Nullable<int> _maKhoa;
		
		private System.Nullable<int> _maHe;
		
		private EntitySet<GV_Mon_Lop> _GV_Mon_Lops;
		
		private EntitySet<SinhVien> _SinhViens;
		
		private EntityRef<HeDaoTao> _HeDaoTao;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLopHocChanging(int value);
    partial void OnmaLopHocChanged();
    partial void OntenLopChanging(string value);
    partial void OntenLopChanged();
    partial void OnkhaiGiangChanging(System.Nullable<System.DateTime> value);
    partial void OnkhaiGiangChanged();
    partial void OntotNghiepChanging(System.Nullable<System.DateTime> value);
    partial void OntotNghiepChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    partial void OnmaKhoaChanging(System.Nullable<int> value);
    partial void OnmaKhoaChanged();
    partial void OnmaHeChanging(System.Nullable<int> value);
    partial void OnmaHeChanged();
    #endregion
		
		public LopHoc()
		{
			this._GV_Mon_Lops = new EntitySet<GV_Mon_Lop>(new Action<GV_Mon_Lop>(this.attach_GV_Mon_Lops), new Action<GV_Mon_Lop>(this.detach_GV_Mon_Lops));
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			this._HeDaoTao = default(EntityRef<HeDaoTao>);
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLopHoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maLopHoc
		{
			get
			{
				return this._maLopHoc;
			}
			set
			{
				if ((this._maLopHoc != value))
				{
					this.OnmaLopHocChanging(value);
					this.SendPropertyChanging();
					this._maLopHoc = value;
					this.SendPropertyChanged("maLopHoc");
					this.OnmaLopHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLop", DbType="NVarChar(100)")]
		public string tenLop
		{
			get
			{
				return this._tenLop;
			}
			set
			{
				if ((this._tenLop != value))
				{
					this.OntenLopChanging(value);
					this.SendPropertyChanging();
					this._tenLop = value;
					this.SendPropertyChanged("tenLop");
					this.OntenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khaiGiang", DbType="Date")]
		public System.Nullable<System.DateTime> khaiGiang
		{
			get
			{
				return this._khaiGiang;
			}
			set
			{
				if ((this._khaiGiang != value))
				{
					this.OnkhaiGiangChanging(value);
					this.SendPropertyChanging();
					this._khaiGiang = value;
					this.SendPropertyChanged("khaiGiang");
					this.OnkhaiGiangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totNghiep", DbType="Date")]
		public System.Nullable<System.DateTime> totNghiep
		{
			get
			{
				return this._totNghiep;
			}
			set
			{
				if ((this._totNghiep != value))
				{
					this.OntotNghiepChanging(value);
					this.SendPropertyChanging();
					this._totNghiep = value;
					this.SendPropertyChanged("totNghiep");
					this.OntotNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="Int")]
		public System.Nullable<int> maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHe", DbType="Int")]
		public System.Nullable<int> maHe
		{
			get
			{
				return this._maHe;
			}
			set
			{
				if ((this._maHe != value))
				{
					if (this._HeDaoTao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHeChanging(value);
					this.SendPropertyChanging();
					this._maHe = value;
					this.SendPropertyChanged("maHe");
					this.OnmaHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_GV_Mon_Lop", Storage="_GV_Mon_Lops", ThisKey="maLopHoc", OtherKey="maLopHoc")]
		public EntitySet<GV_Mon_Lop> GV_Mon_Lops
		{
			get
			{
				return this._GV_Mon_Lops;
			}
			set
			{
				this._GV_Mon_Lops.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_SinhVien", Storage="_SinhViens", ThisKey="maLopHoc", OtherKey="maLopHoc")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HeDaoTao_LopHoc", Storage="_HeDaoTao", ThisKey="maHe", OtherKey="maHe", IsForeignKey=true)]
		public HeDaoTao HeDaoTao
		{
			get
			{
				return this._HeDaoTao.Entity;
			}
			set
			{
				HeDaoTao previousValue = this._HeDaoTao.Entity;
				if (((previousValue != value) 
							|| (this._HeDaoTao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HeDaoTao.Entity = null;
						previousValue.LopHocs.Remove(this);
					}
					this._HeDaoTao.Entity = value;
					if ((value != null))
					{
						value.LopHocs.Add(this);
						this._maHe = value.maHe;
					}
					else
					{
						this._maHe = default(Nullable<int>);
					}
					this.SendPropertyChanged("HeDaoTao");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_LopHoc", Storage="_Khoa", ThisKey="maKhoa", OtherKey="maKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.LopHocs.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.LopHocs.Add(this);
						this._maKhoa = value.maKhoa;
					}
					else
					{
						this._maKhoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GV_Mon_Lops(GV_Mon_Lop entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = this;
		}
		
		private void detach_GV_Mon_Lops(GV_Mon_Lop entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = null;
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonHoc")]
	public partial class MonHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maMonHoc;
		
		private string _tenMonHoc;
		
		private System.Nullable<int> _hocKy;
		
		private System.Nullable<int> _thoiGianHoc;
		
		private System.Nullable<int> _trangThai;
		
		private EntitySet<Diem> _Diems;
		
		private EntitySet<DiemDanh> _DiemDanhs;
		
		private EntitySet<GV_Mon> _GV_Mons;
		
		private EntitySet<GV_Mon_Lop> _GV_Mon_Lops;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaMonHocChanging(int value);
    partial void OnmaMonHocChanged();
    partial void OntenMonHocChanging(string value);
    partial void OntenMonHocChanged();
    partial void OnhocKyChanging(System.Nullable<int> value);
    partial void OnhocKyChanged();
    partial void OnthoiGianHocChanging(System.Nullable<int> value);
    partial void OnthoiGianHocChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public MonHoc()
		{
			this._Diems = new EntitySet<Diem>(new Action<Diem>(this.attach_Diems), new Action<Diem>(this.detach_Diems));
			this._DiemDanhs = new EntitySet<DiemDanh>(new Action<DiemDanh>(this.attach_DiemDanhs), new Action<DiemDanh>(this.detach_DiemDanhs));
			this._GV_Mons = new EntitySet<GV_Mon>(new Action<GV_Mon>(this.attach_GV_Mons), new Action<GV_Mon>(this.detach_GV_Mons));
			this._GV_Mon_Lops = new EntitySet<GV_Mon_Lop>(new Action<GV_Mon_Lop>(this.attach_GV_Mon_Lops), new Action<GV_Mon_Lop>(this.detach_GV_Mon_Lops));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonHoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maMonHoc
		{
			get
			{
				return this._maMonHoc;
			}
			set
			{
				if ((this._maMonHoc != value))
				{
					this.OnmaMonHocChanging(value);
					this.SendPropertyChanging();
					this._maMonHoc = value;
					this.SendPropertyChanged("maMonHoc");
					this.OnmaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMonHoc", DbType="NVarChar(200)")]
		public string tenMonHoc
		{
			get
			{
				return this._tenMonHoc;
			}
			set
			{
				if ((this._tenMonHoc != value))
				{
					this.OntenMonHocChanging(value);
					this.SendPropertyChanging();
					this._tenMonHoc = value;
					this.SendPropertyChanged("tenMonHoc");
					this.OntenMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hocKy", DbType="Int")]
		public System.Nullable<int> hocKy
		{
			get
			{
				return this._hocKy;
			}
			set
			{
				if ((this._hocKy != value))
				{
					this.OnhocKyChanging(value);
					this.SendPropertyChanging();
					this._hocKy = value;
					this.SendPropertyChanged("hocKy");
					this.OnhocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianHoc", DbType="Int")]
		public System.Nullable<int> thoiGianHoc
		{
			get
			{
				return this._thoiGianHoc;
			}
			set
			{
				if ((this._thoiGianHoc != value))
				{
					this.OnthoiGianHocChanging(value);
					this.SendPropertyChanging();
					this._thoiGianHoc = value;
					this.SendPropertyChanged("thoiGianHoc");
					this.OnthoiGianHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_Diem", Storage="_Diems", ThisKey="maMonHoc", OtherKey="maMonHoc")]
		public EntitySet<Diem> Diems
		{
			get
			{
				return this._Diems;
			}
			set
			{
				this._Diems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_DiemDanh", Storage="_DiemDanhs", ThisKey="maMonHoc", OtherKey="maMonHoc")]
		public EntitySet<DiemDanh> DiemDanhs
		{
			get
			{
				return this._DiemDanhs;
			}
			set
			{
				this._DiemDanhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_GV_Mon", Storage="_GV_Mons", ThisKey="maMonHoc", OtherKey="maMonHoc")]
		public EntitySet<GV_Mon> GV_Mons
		{
			get
			{
				return this._GV_Mons;
			}
			set
			{
				this._GV_Mons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_GV_Mon_Lop", Storage="_GV_Mon_Lops", ThisKey="maMonHoc", OtherKey="maMonHoc")]
		public EntitySet<GV_Mon_Lop> GV_Mon_Lops
		{
			get
			{
				return this._GV_Mon_Lops;
			}
			set
			{
				this._GV_Mon_Lops.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = this;
		}
		
		private void detach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = null;
		}
		
		private void attach_DiemDanhs(DiemDanh entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = this;
		}
		
		private void detach_DiemDanhs(DiemDanh entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = null;
		}
		
		private void attach_GV_Mons(GV_Mon entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = this;
		}
		
		private void detach_GV_Mons(GV_Mon entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = null;
		}
		
		private void attach_GV_Mon_Lops(GV_Mon_Lop entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = this;
		}
		
		private void detach_GV_Mon_Lops(GV_Mon_Lop entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maSV;
		
		private string _hoSV;
		
		private string _tenSV;
		
		private System.Nullable<bool> _gioiTinh;
		
		private System.Nullable<System.DateTime> _sinhNhat;
		
		private string _diaChi;
		
		private string _soCMT;
		
		private string _sDT;
		
		private string _email;
		
		private System.Nullable<int> _trangThai;
		
		private System.Nullable<int> _maLopHoc;
		
		private string _anh;
		
		private EntitySet<Diem> _Diems;
		
		private EntitySet<DiemDanh> _DiemDanhs;
		
		private EntityRef<LopHoc> _LopHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSVChanging(int value);
    partial void OnmaSVChanged();
    partial void OnhoSVChanging(string value);
    partial void OnhoSVChanged();
    partial void OntenSVChanging(string value);
    partial void OntenSVChanged();
    partial void OngioiTinhChanging(System.Nullable<bool> value);
    partial void OngioiTinhChanged();
    partial void OnsinhNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnsinhNhatChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsoCMTChanging(string value);
    partial void OnsoCMTChanged();
    partial void OnsDTChanging(string value);
    partial void OnsDTChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    partial void OnmaLopHocChanging(System.Nullable<int> value);
    partial void OnmaLopHocChanged();
    partial void OnanhChanging(string value);
    partial void OnanhChanged();
    #endregion
		
		public SinhVien()
		{
			this._Diems = new EntitySet<Diem>(new Action<Diem>(this.attach_Diems), new Action<Diem>(this.detach_Diems));
			this._DiemDanhs = new EntitySet<DiemDanh>(new Action<DiemDanh>(this.attach_DiemDanhs), new Action<DiemDanh>(this.detach_DiemDanhs));
			this._LopHoc = default(EntityRef<LopHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoSV", DbType="NVarChar(100)")]
		public string hoSV
		{
			get
			{
				return this._hoSV;
			}
			set
			{
				if ((this._hoSV != value))
				{
					this.OnhoSVChanging(value);
					this.SendPropertyChanging();
					this._hoSV = value;
					this.SendPropertyChanged("hoSV");
					this.OnhoSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSV", DbType="NVarChar(100)")]
		public string tenSV
		{
			get
			{
				return this._tenSV;
			}
			set
			{
				if ((this._tenSV != value))
				{
					this.OntenSVChanging(value);
					this.SendPropertyChanging();
					this._tenSV = value;
					this.SendPropertyChanged("tenSV");
					this.OntenSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="Bit")]
		public System.Nullable<bool> gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinhNhat", DbType="Date")]
		public System.Nullable<System.DateTime> sinhNhat
		{
			get
			{
				return this._sinhNhat;
			}
			set
			{
				if ((this._sinhNhat != value))
				{
					this.OnsinhNhatChanging(value);
					this.SendPropertyChanging();
					this._sinhNhat = value;
					this.SendPropertyChanged("sinhNhat");
					this.OnsinhNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(300)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCMT", DbType="NVarChar(15)")]
		public string soCMT
		{
			get
			{
				return this._soCMT;
			}
			set
			{
				if ((this._soCMT != value))
				{
					this.OnsoCMTChanging(value);
					this.SendPropertyChanging();
					this._soCMT = value;
					this.SendPropertyChanged("soCMT");
					this.OnsoCMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDT", DbType="NVarChar(15)")]
		public string sDT
		{
			get
			{
				return this._sDT;
			}
			set
			{
				if ((this._sDT != value))
				{
					this.OnsDTChanging(value);
					this.SendPropertyChanging();
					this._sDT = value;
					this.SendPropertyChanged("sDT");
					this.OnsDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(200)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLopHoc", DbType="Int")]
		public System.Nullable<int> maLopHoc
		{
			get
			{
				return this._maLopHoc;
			}
			set
			{
				if ((this._maLopHoc != value))
				{
					if (this._LopHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLopHocChanging(value);
					this.SendPropertyChanging();
					this._maLopHoc = value;
					this.SendPropertyChanged("maLopHoc");
					this.OnmaLopHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="NVarChar(100)")]
		public string anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_Diem", Storage="_Diems", ThisKey="maSV", OtherKey="maSV")]
		public EntitySet<Diem> Diems
		{
			get
			{
				return this._Diems;
			}
			set
			{
				this._Diems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DiemDanh", Storage="_DiemDanhs", ThisKey="maSV", OtherKey="maSV")]
		public EntitySet<DiemDanh> DiemDanhs
		{
			get
			{
				return this._DiemDanhs;
			}
			set
			{
				this._DiemDanhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_SinhVien", Storage="_LopHoc", ThisKey="maLopHoc", OtherKey="maLopHoc", IsForeignKey=true)]
		public LopHoc LopHoc
		{
			get
			{
				return this._LopHoc.Entity;
			}
			set
			{
				LopHoc previousValue = this._LopHoc.Entity;
				if (((previousValue != value) 
							|| (this._LopHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LopHoc.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._LopHoc.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._maLopHoc = value.maLopHoc;
					}
					else
					{
						this._maLopHoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("LopHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
		
		private void attach_DiemDanhs(DiemDanh entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_DiemDanhs(DiemDanh entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
	}
}
#pragma warning restore 1591
